# Generated by Django 6.0.1 on 2026-02-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100)),
                ('carmodel', models.CharField(max_length=100)),
                ('carcolor', models.CharField(max_length=100, null=True)),
                ('caryear', models.IntegerField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productprice', models.FloatField()),
                ('productdesc', models.TextField()),
                ('productstatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('studentage', models.IntegerField()),
                ('studentcontect', models.CharField(max_length=15, null=True)),
                ('studentcity', models.CharField(max_length=100)),
                ('studentemail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
