# Generated by Django 6.0.1 on 2026-02-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_category_services_studentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(max_length=200)),
                ('bookauthor', models.CharField(max_length=100)),
                ('bookpublisher', models.CharField(max_length=100)),
                ('bookprice', models.FloatField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('employeeage', models.IntegerField()),
                ('employeecity', models.CharField(max_length=100)),
                ('employeeemail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=100)),
                ('teacherage', models.IntegerField()),
                ('teachercity', models.CharField(max_length=100)),
                ('teacheremail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Employeedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeaddress', models.CharField(max_length=200)),
                ('employeequalification', models.CharField(max_length=100)),
                ('employeeexperience', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.employee')),
            ],
            options={
                'db_table': 'employeedetail',
            },
        ),
        migrations.CreateModel(
            name='LibraryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=100)),
                ('memberemail', models.EmailField(max_length=254)),
                ('memberphone', models.CharField(max_length=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.book')),
            ],
            options={
                'db_table': 'librarymember',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=100)),
                ('subjectcode', models.CharField(max_length=20)),
                ('subjectdesc', models.TextField()),
                ('subjectteacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.teacher')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
