# Generated by Django 6.0.1 on 2026-02-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_book_employee_teacher_employeedetail_librarymember_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee1',
        ),
        migrations.AlterModelTable(
            name='employee1',
            table='employee1',
        ),
    ]
