# Generated by Django 6.0.1 on 2026-02-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_employee_employee1_alter_employee1_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarymember',
            name='member',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subjectteacher',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='LibraryMember',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='services',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
